source 'https://github.com/CocoaPods/Specs.git'

target 'OAStackView_Example' do
  pod "OAStackView", :path => "../"
  pod 'Reveal-iOS-SDK', '~> 1.6.2'
end

target 'OAStackView_Tests' do
  pod "OAStackView", :path => "../"
  pod 'Kiwi'
end
